// CNSFileToAST.cpp — Pipeline stage that reads a CNS source file and produces an AST.
//
// Part of Sourcy — CNS -> Lua compiler for MUGEN-style characters.
// Licensed under the MIT License. See LICENSE in the project root.
//
// Author: Miguel Angel Exposito Sanchez (radexx), 2012.

#include "CNSFileToAST.h"
#include "antlr3customtokenstream.h"
#include <iostream>

CNSFileToAST::CNSFileToAST(Pipeline * p) : PipelineStage(p, ED_FILE, ED_AST)
{
	m_input		= nullptr;
	m_lxr		= nullptr;
	m_tstream	= nullptr;
	m_psr		= nullptr;
}

CNSFileToAST::~CNSFileToAST()
{
	CNSFileToAST::reset();
}

void CNSFileToAST::reset()
{
	PipelineStage::reset();
	if(m_psr)
	{
		m_psr->free(m_psr); m_psr = nullptr;
	}
	if(m_tstream)
	{
		m_tstream->free(m_tstream);	m_tstream	= nullptr;
	}
	if(m_lxr)
	{
		m_lxr->free(m_lxr);	m_lxr = nullptr;
	}
	if(m_input)
	{	
		m_input->close(m_input); m_input = nullptr;
	}

}

void CNSFileToAST::run()
{
	reset();

	m_input	= antlr3FileStreamNew((pANTLR3_UINT8)m_filename.c_str(), ANTLR3_ENC_UTF8);

	if (m_input == nullptr)
    {
		std::cerr << "Unable to open file " << m_filename << std::endl;
		++m_nErrors;
		return;
	}

	// Case insensitivity
	m_input->setUcaseLA(m_input, ANTLR3_TRUE);

	m_lxr	    = cnsLexerNew(m_input);	    // xxxLexerNew is generated by ANTLR

	if ( m_lxr == nullptr )
    {
		std::cerr << "Unable to create the lexer due to malloc() failure!" << std::endl;
		++m_nErrors;
		return;
    }

	m_tstream = antlr3CustomTokenStreamSourceNew(ANTLR3_SIZE_HINT, TOKENSOURCE(m_lxr));

	if (m_tstream == nullptr)
    {
		std::cerr << "Out of memory trying to allocate token stream" << std::endl;
		++m_nErrors;
		return;
    }

	m_psr	    = cnsParserNew(reinterpret_cast<pANTLR3_COMMON_TOKEN_STREAM>(m_tstream));  // xxxParserNew is generated by ANTLR3
    
	if (m_psr == nullptr)
    {
		std::cerr << "Out of memory trying to allocate parser" << std::endl;
		++m_nErrors;
		return;
    }

	// Here is where the parsing takes place
	m_cnsAST = m_psr->cns(m_psr);
	////

	m_nErrors = m_psr->pParser->rec->state->errorCount;
	
	if(m_nErrors > 0)
	{	
		return;
	}
}
